[mypy]
# Indica ao mypy que ele deve procurar os módulos dentro da pasta 'app'
mypy_path = app

# Evita erros visuais de imports de bibliotecas que não têm tipagem (como o PySpark)
ignore_missing_imports = True

# Força o mypy a usar apenas as bases explícitas, resolvendo o erro de "Source file found twice"
explicit_package_bases = True